[package]
name = "day-16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
crossterm = "0.27.0"
=======
>>>>>>> b2f61c128398c7bed22a1f206237ee6eeb15903a
